[package]
name = "bevy_console"
version = "0.3.1"
edition = "2021"
authors = ["RichoDemus <git@richodemus.com>"]
homepage = "https://github.com/RichoDemus/bevy-console"
repository = "https://github.com/RichoDemus/bevy-console"
description = "dev console for bevy"
license = "MIT"
readme = "README.md"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_console_derive = { path = "./bevy_console_derive", version = "0.3.0" }
bevy_console_parser = { path = "./bevy_console_parser", version = "0.3.0" }
bevy_egui = { git = "https://github.com/brandon-reinhart/bevy_egui", branch = "0.8-dev" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }

[workspace]
members = ["bevy_console_derive", "bevy_console_parser"]
