[package]
name = "bevy_console"
version = "0.2.4"
edition = "2021"
authors = ["RichoDemus <git@richodemus.com>"]
homepage = "https://github.com/RichoDemus/bevy-console"
repository = "https://github.com/RichoDemus/bevy-console"
description = "dev console for bevy"
license = "MIT"
readme = "README.md"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
bevy_console_derive = { path = "./bevy_console_derive" }
bevy_console_parser = { path = "./bevy_console_parser" }
bevy_egui = { path = "/tmp/bevy_egui" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }

[workspace]
members = ["bevy_console_derive", "bevy_console_parser"]
